<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheel">

    <xacro:macro name="wheel" params="prefix reflect">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rabbitamr_description/meshes/wheel.stl" scale="0.0025 0.0025 0.0025"/>
                </geometry>
                <material name="orange"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${radians(90)} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <axis xyz="0 1 0" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="0 ${wheel_separation/2 * reflect} ${wheel_radius - base_distance_from_ground - (base_height/2)}"
                    rpy="0 0 0"/>
        </joint>

        <transmission name="${prefix}_wheel_trans" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${prefix}_wheel_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${prefix}_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>
    </xacro:macro>
</robot>