resolution: 0.05

robot_base_frame: base_footprint

update_frequency: 10.0
publish_frequency: 10.0
transform_tolerance: 0.5

obstacle_range: 5.0 # the obstacles that are going to be put in local costmap
raytrace_range: 6.0 # the range that is going to be considered for clearing path


obstacles_layer:
  observation_sources: laser d435i_laser

  laser: {
    sensor_frame: sicklidar,
    data_type: LaserScan,
    clearing: true,
    marking: true,
    topic: /sick_safetyscanners/scan,
    inf_is_valid: true
  }

  d435i_laser: {
    sensor_frame: d435i,
    data_type: LaserScan,
    clearing: true,
    marking: true,
    topic: /scan,
    inf_is_valid: true
  }

static_layer:
  map_topic: /map
  subscribe_to_updates: true

