odom_frame: odom
base_link_frame: base_footprint
world_frame: odom
#map_frame: map

two_d_mode: true

frequency: 20 # <============= change this

odom0: rabbitamr_diff_drive_controller/odom
odom0_config: [false, false, false,
               false, false, true,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10

imu0: t265/imu
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              true, false, false]
imu0_differential: false
imu0_queue_size: 10

